### ISSUE TITLE
Absent rejected

### ISSUE THREAD

**Issue by RobyCigar** [cloudenum/presensi-amikom#1]
I already input with my correct NIM and code from my lecturer but somehow my form was rejected. 

Anyway, can I do PR on this project?

Thank you

![image](https://user-images.githubusercontent.com/69680330/113088001-f1de3080-920e-11eb-88e7-3ab43d349a11.png)

**Comment by cloudenum** [comment]
that because the process to generate the encryption key has changed, I just doesn't have time to fix it

yes, of course you can make any contribution you would like.
